# Generated by Django 4.2.3 on 2023-11-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolstore_app', '0002_remove_department_year_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
